#!/bin/sh
#
# tornado        Starts a TOR proxy
#

start() {
    echo "Starting tornado"

    # Setup AP
    sysctl -w net.ipv4.ip_forward=1
    iptables-restore /etc/iptables.ipv4
    ifup wlan0
    dnsmasq
    hostapd -B /etc/hostapd.conf
    rdate -s time.nist.gov
    
    # Setup TOR
    if [ ! -e /var/log/tor/notices.log ]; then
        mkdir -p /var/log/tor/
        touch /var/log/tor/notices.log
        mkdir -p /var/log/misc/tor
    fi
    chown -R nobody /var/lib/misc/tor
    chown -R nobody /var/log/tor/

    tor

    echo OK
}

stop() {
    echo "Stopping tornado"
    killall -q tor hostapd dnsmasq
    ifdown wlan0
    echo OK
}

restart() {
    stop
    start
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart | reload)
    restart
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
