#!/bin/sh
#
# tornado        Starts the isolating TOR proxy
#

start() {
    echo "Starting tornado"

    # Update wpa_supplicant.conf file
    mkdir -p /boot
    mount -t vfat /dev/mmcblk0p1 /boot
    [ -e /boot/wpa_supplicant.conf ] && cp /boot/wpa_supplicant.conf /etc
    umount /boot
    rmdir /boot

    # Starting wlan0
    ifup wlan0

    # Restore iptables rules
    sysctl -w net.ipv4.ip_forward=1
    iptables-restore /etc/iptables.ipv4

    # Setup TOR
    if [ ! -e /var/log/tor/notices.log ]; then
        mkdir -p /var/log/tor/
        touch /var/log/tor/notices.log
        mkdir -p /var/log/misc/tor
    fi
    chown -R nobody /var/lib/misc/tor
    chown -R nobody /var/log/tor/

    # Starting ap0
    ifup ap0

    # Setting up hostapd
    CHANNEL=$(iw dev wlan0 info | awk '/channel/ {print $2}')
    sed -i "s/channel=[0-9]*/channel=$CHANNEL/" /etc/hostapd.conf
    hostapd -B /etc/hostapd.conf

    tor

    echo OK
}

stop() {
    echo "Stopping tornado"
    killall -q hostapd
    ifdown ap0
    ifdown wlan0
    echo "OK"
}

restart() {
    stop
    start
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart | reload)
    restart
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
